FROM node:18.18-alpine

WORKDIR /usr/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "run", "start:dev", "--", "--preserveWatchOutput"]
# CMD ["node", "--inspect=0.0.0.0:9229", "src/app/index.ts"]