version: '3.8'
services:
  api:
    container_name: glasgow-api
    image: node:18.18-alpine
    restart: always
    tty: true
    depends_on:
      - db
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: '/usr/app'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
    command: >
      sh -c "npm install &&
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run start:dev -- --preserveWatchOutput"
    networks:
      - glasgow-network

  db:
    image: mysql
    restart: always
    container_name: mysql-glasgow
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - glasgow-network

networks:
  glasgow-network:
    driver: bridge